(function(){
  const day = Number(document.body.dataset.day);
  const lessons = window.ATLAS_LESSON_BATCH || [];
  const lesson = lessons.find(item => item.day === day);
  if (!lesson) { document.body.innerHTML = '<p style="padding:30px">Lesson unavailable.</p>'; return; }
  const index = lessons.findIndex(item => item.day === day);
  const previous = day === 4 ? {href:'day-03-liability-tax-impact.html',title:'Day 3'} : lessons[index-1];
  const next = lessons[index+1] || {href:'30-day-tax-office-launch.html#roadmap',title:'Course roadmap'};
  const hrefFor = item => item.href || `day-${String(item.day).padStart(2,'0')}-${item.slug}.html`;
  const worksheet = `downloads/Day-${String(day).padStart(2,'0')}-${lesson.slug.split('-').map(w=>w[0].toUpperCase()+w.slice(1)).join('-')}-Worksheet.pdf`;
  const key = `atlas-30day-day-${day}-v1`;
  const defaults = {reviewed:false,downloads:[],plan:false,questions:false,quiz:false,completed:false,fields:{},questionsText:'',notes:''};
  let state; try { state={...defaults,...JSON.parse(localStorage.getItem(key)||'{}')}; } catch { state={...defaults}; }
  state.fields = state.fields || {};
  const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const points = lesson.key_points.map((p,i)=>`<article class="point-card"><b>0${i+1}</b><h4>${escapeHtml(p[0])}</h4><p>${escapeHtml(p[1])}</p></article>`).join('');
  const fields = lesson.fields.map((f,i)=>`<label>${escapeHtml(f[0])}<input id="planField${i}" value="${escapeHtml(state.fields[i]||'')}" placeholder="${escapeHtml(f[1])}"></label>`).join('');
  const quiz = lesson.quiz.map((q,i)=>`<fieldset><legend>${i+1}. ${escapeHtml(q[0])}</legend>${q[1].map((option,j)=>`<label><input type="radio" name="q${i+1}" value="${j}"><span>${escapeHtml(option)}</span></label>`).join('')}</fieldset>`).join('');
  const videoPaths = {
    4:'assets/Day-04-Secure-Your-EIN.mp4',
    5:'assets/Day-05-Form-Your-Legal-Entity.mp4',
    6:'assets/Day-06-Open-Your-Business-Bank-Account.mp4',
    7:'assets/Day-07-Build-Your-Startup-Record-File.mp4',
    8:'assets/Day-08-Obtain-Your-PTIN.mp4'
  };
  const videoBrief = videoPaths[day]
    ? `<div class="lesson-video-frame"><video controls preload="metadata" aria-label="Day ${day}: ${escapeHtml(lesson.title)} video"><source src="${videoPaths[day]}" type="video/mp4">Your browser does not support embedded video.</video></div>`
    : `<div class="video-brief"><img src="assets/Nova_Talia_Profile.jpg" alt="Nova Grant"><div><span>NOVA VIDEO BRIEFING</span><h3>${escapeHtml(lesson.title)}</h3><p>The toolkit-derived production script is prepared for the Nova video workflow.</p></div></div>`;
  document.body.innerHTML = `
    <aside class="batch-sidebar"><a class="batch-logo" href="index.html"><img src="assets/Atlas_Academy_Logo.png" alt="Atlas Academy"></a><nav><a href="30-day-tax-office-launch.html"><span>&larr;</span>Course Mission Control</a><a class="active" href="#mission"><span>01</span>Mission Brief</a><a href="#lesson"><span>02</span>Lesson</a><a href="#action"><span>03</span>Action Plan</a><a href="#checkpoint"><span>04</span>Checkpoint</a></nav><div class="batch-instructor"><img src="assets/Nova_Talia_Profile.jpg" alt="Nova Grant"><div><p>COURSE INSTRUCTOR</p><strong>Nova Grant</strong><small>LAUNCH COMMANDER</small></div></div><img class="batch-tcp" src="assets/tax-compliance-pro-logo-dark.webp" alt="Tax Compliance Pro"></aside>
    <main class="batch-main"><header class="batch-topbar"><div><p>${escapeHtml(lesson.phase)}</p><h1>Day ${day}: ${escapeHtml(lesson.title)}</h1></div><div class="batch-progress"><span id="headerProgress">0 of 5 complete</span><div><i id="headerProgressBar"></i></div></div></header>
    <div class="batch-wrap"><section class="batch-hero" id="mission"><div><span class="eyebrow">DAY ${String(day).padStart(2,'0')} / TOOLKIT MISSION</span><h2>${escapeHtml(lesson.tagline)}</h2><p>${escapeHtml(lesson.summary)}</p><div class="batch-stats"><div><b>${escapeHtml(lesson.duration)}</b><small>MINUTES</small></div><div><b>${lesson.xp}</b><small>XP</small></div><div><b>${escapeHtml(lesson.toolkit_pages)}</b><small>TOOLKIT PAGES</small></div></div></div><div class="batch-nova"><img src="assets/Nova_Talia_Profile.jpg" alt="Nova Grant"><strong>NOVA GRANT</strong><small>LAUNCH COMMANDER</small></div></section>
    <div class="batch-grid"><article class="batch-card"><div class="batch-tabs" role="tablist"><button class="active" data-tab="lessonPanel">Lesson</button><button data-tab="actionPanel">Action Plan</button><button data-tab="downloadsPanel">Downloads</button><button data-tab="quizPanel">Quiz</button><button data-tab="notesPanel">Notes</button></div>
      <section class="batch-panel active" id="lessonPanel">${videoBrief}<p class="section-kicker" id="lesson">TOOLKIT LESSON</p><h3>${escapeHtml(lesson.title)}</h3><p>${escapeHtml(lesson.summary)}</p><div class="point-grid">${points}</div><div class="source-note"><strong>Curriculum source:</strong> 30 Day Tax Office Launch Toolkit, pages ${escapeHtml(lesson.toolkit_pages)}. Verify current government, state, legal, tax, banking, insurance, and vendor requirements with official sources and qualified professionals.</div><label class="review-check"><input type="checkbox" id="lessonReviewed"><span>I reviewed the Day ${day} lesson and understand the mission.</span></label></section>
      <section class="batch-panel" id="actionPanel"><p class="section-kicker" id="action">DAY ${day} ACTION PLAN</p><h3>${escapeHtml(lesson.action_title)}</h3><p>${escapeHtml(lesson.action_intro)}</p><div class="field-grid">${fields}</div><label class="notes-label">${escapeHtml(lesson.professional_prompt)}<textarea id="questionsText" placeholder="Record questions, dependencies, and items to verify..."></textarea></label><div class="save-row"><button class="primary-action" id="savePlan">Save Action Plan</button><span id="planStatus">Not saved</span></div></section>
      <section class="batch-panel" id="downloadsPanel"><p class="section-kicker">DAY ${day} DOWNLOADS</p><h3>Mission resources</h3><div class="download-list"><a href="${worksheet}" target="_blank" data-download="worksheet"><span>PDF</span><div><strong>Day ${day} Action Worksheet</strong><small>Printable planner and professional-review questions</small></div><b>Open</b></a><a href="downloads/30-Day-Tax-Office-Launch-Toolkit.pdf#page=${String(lesson.toolkit_pages).split('-')[0]}" target="_blank" data-download="toolkit"><span>PDF</span><div><strong>30 Day Tax Office Launch Toolkit</strong><small>Source reading: pages ${escapeHtml(lesson.toolkit_pages)}</small></div><b>Open</b></a></div></section>
      <section class="batch-panel" id="quizPanel"><p class="section-kicker">DAY ${day} CHECKPOINT</p><h3>Check your understanding</h3><form class="batch-quiz" id="dayQuiz">${quiz}<div class="save-row"><button class="primary-action" type="submit">Submit Quiz</button><span id="quizStatus">Not attempted</span></div></form></section>
      <section class="batch-panel" id="notesPanel"><p class="section-kicker">PRIVATE NOTES</p><h3>Day ${day} notes</h3><label class="notes-label">Mission notes<textarea id="lessonNotes" placeholder="Your notes are stored on this device..."></textarea></label><div class="save-row"><button class="primary-action" id="saveNotes">Save Notes</button><span id="notesStatus">Not saved</span></div></section>
    </article><aside class="batch-card batch-checklist" id="checkpoint"><p>DAY ${day} CHECKLIST</p><h3>Unlock Day ${day+1}</h3><div class="requirement-list"><div class="requirement" data-requirement="reviewed"><i></i><span>Review Nova's lesson</span><b>Pending</b></div><div class="requirement" data-requirement="downloads"><i></i><span>Open both resources</span><b>0 of 2</b></div><div class="requirement" data-requirement="plan"><i></i><span>Save action plan</span><b>Pending</b></div><div class="requirement" data-requirement="questions"><i></i><span>Record review questions</span><b>Pending</b></div><div class="requirement" data-requirement="quiz"><i></i><span>Pass quiz at 80%</span><b>Pending</b></div></div><button class="complete-day" id="completeDay" disabled>Complete Day ${day}</button><small class="completion-help" id="completionHelp">Complete all five requirements to unlock Day ${day+1}.</small><div class="prev-next"><a href="${hrefFor(previous)}">&larr; ${escapeHtml(previous.title)}</a><a href="${hrefFor(next)}">${escapeHtml(next.title)} &rarr;</a></div></aside></div></div></main>
    <div class="completion-modal" id="completionModal" hidden><div><div class="number">${day+1}</div><span>DAY ${day+1} UNLOCKED</span><h2>Day ${day} Complete</h2><p>Your Day ${day} action plan is saved. Continue when you are ready.</p><a href="${hrefFor(next)}">Continue to ${escapeHtml(next.title)}</a></div></div>`;
  const save = () => localStorage.setItem(key,JSON.stringify(state));
  document.querySelectorAll('.batch-tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.batch-tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.batch-panel').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.tab).classList.add('active');}));
  document.getElementById('lessonReviewed').checked=state.reviewed;document.getElementById('questionsText').value=state.questionsText||'';document.getElementById('lessonNotes').value=state.notes||'';
  document.getElementById('lessonReviewed').addEventListener('change',e=>{state.reviewed=e.target.checked;save();render();});
  document.querySelectorAll('[data-download]').forEach(link=>link.addEventListener('click',()=>{if(!state.downloads.includes(link.dataset.download))state.downloads.push(link.dataset.download);save();render();}));
  document.getElementById('savePlan').addEventListener('click',()=>{lesson.fields.forEach((_,i)=>state.fields[i]=document.getElementById(`planField${i}`).value.trim());state.questionsText=document.getElementById('questionsText').value.trim();state.plan=lesson.fields.every((_,i)=>Boolean(state.fields[i]));state.questions=Boolean(state.questionsText);document.getElementById('planStatus').textContent=state.plan&&state.questions?'Action plan saved':'Complete every field and add your questions';save();render();});
  document.getElementById('dayQuiz').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const score=lesson.quiz.filter((q,i)=>data.get(`q${i+1}`)!==null&&Number(data.get(`q${i+1}`))===q[2]).length;state.quiz=score>=4;document.getElementById('quizStatus').textContent=state.quiz?`Passed - ${score*20}%`:`${score} of 5 correct - 80% required`;save();render();});
  document.getElementById('saveNotes').addEventListener('click',()=>{state.notes=document.getElementById('lessonNotes').value;document.getElementById('notesStatus').textContent='Notes saved';save();});
  document.getElementById('completeDay').addEventListener('click',()=>{if(!ready())return;state.completed=true;save();document.getElementById('completionModal').hidden=false;});
  const ready=()=>state.reviewed&&state.downloads.length===2&&state.plan&&state.questions&&state.quiz;
  function requirement(name,done,label){const row=document.querySelector(`[data-requirement="${name}"]`);row.classList.toggle('done',done);row.querySelector('b').textContent=done?label:(name==='downloads'?`${state.downloads.length} of 2`:'Pending');}
  function render(){requirement('reviewed',state.reviewed,'Reviewed');requirement('downloads',state.downloads.length===2,'Opened');requirement('plan',state.plan,'Saved');requirement('questions',state.questions,'Recorded');requirement('quiz',state.quiz,'Passed');const count=[state.reviewed,state.downloads.length===2,state.plan,state.questions,state.quiz].filter(Boolean).length;document.getElementById('headerProgress').textContent=`${count} of 5 complete`;document.getElementById('headerProgressBar').style.width=`${count*20}%`;document.getElementById('completeDay').disabled=!ready();document.getElementById('completionHelp').textContent=ready()?`All requirements complete. Day ${day+1} is ready to unlock.`:`Complete all five requirements to unlock Day ${day+1}.`;if(state.plan&&state.questions)document.getElementById('planStatus').textContent='Action plan saved';if(state.quiz)document.getElementById('quizStatus').textContent='Passed';if(state.completed)document.getElementById('completeDay').textContent=`Day ${day} Complete`;}
  render();
})();
